services:
  mysql-server:
    image: mysql:8
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - mynet

  mysql-client:
    image: phpmyadmin
    container_name: mysql-client
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
